# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/alps/8227_demo/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/alps/8227l_demo/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/alps/8227l_demo/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libClearMotionFW.so:$(TARGET_COPY_OUT_VENDOR)/lib/libClearMotionFW.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libdpframework.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdpframework.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libmp2dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmp2dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libmp4enc_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmp4enc_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxCore.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxG711Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxG711Dec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxGsmDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxGsmDec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxMp3Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxMp3Dec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxRawDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxRawDec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxVdecEx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVdecEx.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxVenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVenc.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxVorbisEnc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVorbisEnc.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/librrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/librrc.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvc1dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvc1dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvcodecdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodecdrv.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvcodec_oal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_oal.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvcodec_utility.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_utility.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvp8dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp8dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvp8enc_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp8enc_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvp9dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp9dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd \
    vendor/alps/8227l_demo/proprietary/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd

PRODUCT_COPY_FILES += \
    vendor/alps/8227l_demo/proprietary/bin/audiocmdservice_atci:$(TARGET_COPY_OUT_SYSTEM)/bin/audiocmdservice_atci \
    vendor/alps/8227l_demo/proprietary/bin/mtkcam-debug:$(TARGET_COPY_OUT_SYSTEM)/bin/mtkcam-debug \
    vendor/alps/8227l_demo/proprietary/bin/mtkradiooptions:$(TARGET_COPY_OUT_SYSTEM)/bin/mtkradiooptions \
    vendor/alps/8227l_demo/proprietary/bin/nvram_agent_binder:$(TARGET_COPY_OUT_SYSTEM)/bin/nvram_agent_binder \
    vendor/alps/8227l_demo/proprietary/bin/nvram_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/nvram_daemon \
    vendor/alps/8227l_demo/proprietary/bin/pq:$(TARGET_COPY_OUT_SYSTEM)/bin/pq \
    vendor/alps/8227l_demo/proprietary/bin/wmt_concurrency:$(TARGET_COPY_OUT_SYSTEM)/bin/wmt_concurrency \
    vendor/alps/8227l_demo/proprietary/bin/wmt_launcher:$(TARGET_COPY_OUT_SYSTEM)/bin/wmt_launcher \
    vendor/alps/8227l_demo/proprietary/bin/wmt_loader:$(TARGET_COPY_OUT_SYSTEM)/bin/wmt_loader \
    vendor/alps/8227l_demo/proprietary/bin/wmt_loopback:$(TARGET_COPY_OUT_SYSTEM)/bin/wmt_loopback \
    vendor/alps/8227l_demo/proprietary/bin/xyautocpnavi:$(TARGET_COPY_OUT_SYSTEM)/bin/xyautocpnavi \
    vendor/alps/8227l_demo/proprietary/bin/xydelinsidefiles:$(TARGET_COPY_OUT_SYSTEM)/bin/xydelinsidefiles \
    vendor/alps/8227l_demo/proprietary/bin/xyrminsidefiles:$(TARGET_COPY_OUT_SYSTEM)/bin/xyrminsidefiles \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/bt_did.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/bt_did.conf \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/bt_stack.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/bt_stack.conf \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/mtk_bt_fw.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/mtk_bt_fw.conf \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/mtk_bt_stack.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/mtk_bt_stack.conf \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/xycpdata.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/xycpdata.rc \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/xyremfile.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/xyremfile.rc \
    vendor/alps/8227l_demo/proprietary/etc/clatd.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/clatd.conf \
    vendor/alps/8227l_demo/proprietary/etc/custom.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/custom.conf \
    vendor/alps/8227l_demo/proprietary/etc/factory.ini:$(TARGET_COPY_OUT_SYSTEM)/etc/factory.ini \
    vendor/alps/8227l_demo/proprietary/etc/mtklog-config.prop:$(TARGET_COPY_OUT_SYSTEM)/etc/mtklog-config.prop \

    vendor/alps/8227l_demo/proprietary/lib/hw/android.hidl.memory@1.0-impl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/android.hidl.memory@1.0-impl.so \
    vendor/alps/8227l_demo/proprietary/lib/hw/audio.a2dp.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/audio.a2dp.default.so \
    vendor/alps/8227l_demo/proprietary/lib/hw/bluetooth.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/bluetooth.default.so \
    vendor/alps/8227l_demo/proprietary/lib/hw/keystore.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/keystore.default.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioclient.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiocompensationfilter.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiocomponentengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiocomponentengine.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiocustparam.solibaudiodcrflt.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiodcrflt.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiodcrflt.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioeffect_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioeffect_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioflinger.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioflinger.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiohal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiohal.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiomanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiomanager.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicycustomextensions.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicycustomextensions.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicyenginedefault.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicyenginedefault.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicymanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicymanager.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicymanagerdefault.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicymanagerdefault.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicyservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicyservice.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioprimarydevicehalifclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioprimarydevicehalifclient.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioprocessing.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioprocessing.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudio-resampler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudio-resampler.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiospdif.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiospdif.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiotoolkit.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiotoolkit.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioutils.solibaudioutils.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiowhitelist.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiowhitelist.so \
    vendor/alps/8227l_demo/proprietary/lib/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbessound_hd_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libblisrc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libblisrc.so \
    vendor/alps/8227l_demo/proprietary/lib/libblisrc32.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libblisrc32.so \
    vendor/alps/8227l_demo/proprietary/lib/libbluetoothem_mtk_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetoothem_mtk_system.so \
    vendor/alps/8227l_demo/proprietary/lib/libbluetooth_mtk_pure_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth_mtk_pure_system.so \
    vendor/alps/8227l_demo/proprietary/lib/libbluetooth_relayer_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth_relayer_system.so \
    vendor/alps/8227l_demo/proprietary/lib/libcamera2ndk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera2ndk.so \
    vendor/alps/8227l_demo/proprietary/lib/libcamera_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera_client.so \
    vendor/alps/8227l_demo/proprietary/lib/libcamera_metadata.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera_metadata.so \
    vendor/alps/8227l_demo/proprietary/lib/libcameraservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcameraservice.so \
    vendor/alps/8227l_demo/proprietary/lib/libcustom_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcustom_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libcustom_nvram_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcustom_nvram_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libcustom_prop.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcustom_prop.solibcustom_prop.so \
    vendor/alps/8227l_demo/proprietary/lib/libdrmframework.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdrmframework.so \
    vendor/alps/8227l_demo/proprietary/lib/libdrmframework_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdrmframework_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libem_support_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libem_support_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libfile_op_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfile_op_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libfmjni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfmjni.so \
    vendor/alps/8227l_demo/proprietary/lib/libfmq.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfmq.so \
    vendor/alps/8227l_demo/proprietary/lib/libGdmaScalerPipe.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libGdmaScalerPipe.so \
    vendor/alps/8227l_demo/proprietary/lib/libgralloc_extra_sys.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgralloc_extra_sys.so \
    vendor/alps/8227l_demo/proprietary/lib/libgui.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgui.so \
    vendor/alps/8227l_demo/proprietary/lib/libgui_debug.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgui_debug.so \
    vendor/alps/8227l_demo/proprietary/lib/libhwbinder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhwbinder.so \
    vendor/alps/8227l_demo/proprietary/lib/libhwm_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhwm_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libion.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libion.so \
    vendor/alps/8227l_demo/proprietary/lib/libjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjpeg.so \
    vendor/alps/8227l_demo/proprietary/lib/libJpgDecPipe.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libJpgDecPipe.so \
    vendor/alps/8227l_demo/proprietary/lib/libJpgEncPipe.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libJpgEncPipe.so \
    vendor/alps/8227l_demo/proprietary/lib/libmemtrack.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmemtrack.so \
    vendor/alps/8227l_demo/proprietary/lib/libmhalImageCodec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmhalImageCodec.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkavenhancements.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtkavenhancements.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkbluetooth_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtkbluetooth_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkbootanimation.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtkbootanimation.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtk_drvb_sys.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtk_drvb_sys.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtklimiter.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtklimiter.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkshifter.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtkshifter.so \
    vendor/alps/8227l_demo/proprietary/lib/libnvram_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvram_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libnvram_platform_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvram_platform_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libnvram_sec_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvram_sec_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libRadioInterface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libRadioInterface.so \
    vendor/alps/8227l_demo/proprietary/lib/libradio_metadata.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libradio_metadata.so \
    vendor/alps/8227l_demo/proprietary/lib/libsensor.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsensor.so \
    vendor/alps/8227l_demo/proprietary/lib/libsensorservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsensorservice.so \
    vendor/alps/8227l_demo/proprietary/lib/libsensorservicehidl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsensorservicehidl.so \
    vendor/alps/8227l_demo/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_amrnb_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_amrnb_common.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_enc_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_enc_common.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_flacdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_flacdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_foundation.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_foundation.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_httplive.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_httplive.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_http_support.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_http_support.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_omx.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_omx.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_omx_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_omx_utils.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_aacdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_aacdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_aacenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_aacenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_amrdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_amrdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_amrnbenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_amrnbenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_amrwbenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_amrwbenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_avcdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_avcdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_avcenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_avcenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_flacdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_flacdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_flacenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_flacenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_g711dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_g711dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_gsmdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_gsmdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_hevcdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_hevcdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mp3dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_mp3dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mpeg2dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_mpeg2dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mpeg4dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_mpeg4dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mpeg4enc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_mpeg4enc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_opusdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_opusdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_rawdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_rawdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_vorbisdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_vorbisdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_vpxdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_vpxdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_vpxenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_soft_vpxenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_wfd_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_wfd_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_xmlparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_xmlparser.so \
    vendor/alps/8227l_demo/proprietary/lib/libSwJpgCodec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libSwJpgCodec.so \
    vendor/alps/8227l_demo/proprietary/lib/libui.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libui.so \
    vendor/alps/8227l_demo/proprietary/lib/libui_ext_fwk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libui_ext_fwk.so \
    vendor/alps/8227l_demo/proprietary/lib/libusbdvr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libusbdvr.so \
    vendor/alps/8227l_demo/proprietary/lib/libusbhost.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libusbhost.so