# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/alps/8227_demo/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/alps/8227l_demo/proprietary/vendor/etc/mtk_omx_core.cfg:/vendor/etc/mtk_omx_core.cfg \
    vendor/alps/8227l_demo/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libClearMotionFW.so:/vendor/lib/libClearMotionFW.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libdpframework.so:/vendor/lib/libdpframework.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libmp2dec_sa.ca7.so:/vendor/lib/libmp2dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libmp4enc_sa.ca7.so:/vendor/lib/libmp4enc_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxCore.so:/vendor/lib/libMtkOmxCore.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxG711Dec.so:/vendor/lib/libMtkOmxG711Dec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxGsmDec.so:/vendor/lib/libMtkOmxGsmDec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxMp3Dec.so:/vendor/lib/libMtkOmxMp3Dec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxRawDec.so:/vendor/lib/libMtkOmxRawDec.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxVdecEx.so:/vendor/lib/libMtkOmxVdecEx.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxVenc.so:/vendor/lib/libMtkOmxVenc.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libMtkOmxVorbisEnc.so:/vendor/lib/libMtkOmxVorbisEnc.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/librrc.so:/vendor/lib/librrc.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvc1dec_sa.ca7.so:/vendor/lib/libvc1dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvcodecdrv.so:/vendor/lib/libvcodecdrv.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvcodec_oal.so:/vendor/lib/libvcodec_oal.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvcodec_utility.so:/vendor/lib/libvcodec_utility.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvp8dec_sa.ca7.so:/vendor/lib/libvp8dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvp8enc_sa.ca7.so:/vendor/lib/libvp8enc_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/lib/libvp9dec_sa.ca7.so:/vendor/lib/libvp9dec_sa.ca7.so \
    vendor/alps/8227l_demo/proprietary/vendor/media/LMspeed_508.emd:/vendor/media/LMspeed_508.emd \
    vendor/alps/8227l_demo/proprietary/vendor/media/PFFprec_600.emd:/vendor/media/PFFprec_600.emd

PRODUCT_COPY_FILES += \
    vendor/alps/8227l_demo/proprietary/bin/audiocmdservice_atci:/system/bin/audiocmdservice_atci \
    vendor/alps/8227l_demo/proprietary/bin/mtkcam-debug:/system/bin/mtkcam-debug \
    vendor/alps/8227l_demo/proprietary/bin/mtkradiooptions:/system/bin/mtkradiooptions \
    vendor/alps/8227l_demo/proprietary/bin/nvram_agent_binder:/system/bin/nvram_agent_binder \
    vendor/alps/8227l_demo/proprietary/bin/nvram_daemon:/system/bin/nvram_daemon \
    vendor/alps/8227l_demo/proprietary/bin/pq:/system/bin/pq \
    vendor/alps/8227l_demo/proprietary/bin/wmt_concurrency:/system/bin/wmt_concurrency \
    vendor/alps/8227l_demo/proprietary/bin/wmt_launcher:/system/bin/wmt_launcher \
    vendor/alps/8227l_demo/proprietary/bin/wmt_loader:/system/bin/wmt_loader \
    vendor/alps/8227l_demo/proprietary/bin/wmt_loopback:/system/bin/wmt_loopback \
    vendor/alps/8227l_demo/proprietary/bin/xyautocpnavi:/system/bin/xyautocpnavi \
    vendor/alps/8227l_demo/proprietary/bin/xydelinsidefiles:/system/bin/xydelinsidefiles \
    vendor/alps/8227l_demo/proprietary/bin/xyrminsidefiles:/system/bin/xyrminsidefiles \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/bt_did.conf:/system/etc/bluetooth/bt_did.conf \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/bt_stack.conf:/system/etc/bluetooth/bt_stack.conf \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/mtk_bt_fw.conf:/system/etc/bluetooth/mtk_bt_fw.conf \
    vendor/alps/8227l_demo/proprietary/etc/bluetooth/mtk_bt_stack.conf:/system/etc/bluetooth/mtk_bt_stack.conf \
    vendor/alps/8227l_demo/proprietary/etc/init/xycpdata.rc:/system/etc/init/xycpdata.rc \
    vendor/alps/8227l_demo/proprietary/etc/init/xyremfile.rc:/system/etc/init/xyremfile.rc \
    vendor/alps/8227l_demo/proprietary/etc/clatd.conf:/system/etc/clatd.conf \
    vendor/alps/8227l_demo/proprietary/etc/custom.conf:/system/etc/custom.conf \
    vendor/alps/8227l_demo/proprietary/etc/factory.ini:/system/etc/factory.ini \
    vendor/alps/8227l_demo/proprietary/etc/mtklog-config.prop:/system/etc/mtklog-config.prop \
    vendor/alps/8227l_demo/proprietary/lib/hw/android.hidl.memory@1.0-impl.so:/system/lib/hw/android.hidl.memory@1.0-impl.so \
    vendor/alps/8227l_demo/proprietary/lib/hw/audio.a2dp.default.so:/system/lib/hw/audio.a2dp.default.so \
    vendor/alps/8227l_demo/proprietary/lib/hw/bluetooth.default.so:/system/lib/hw/bluetooth.default.so \
    vendor/alps/8227l_demo/proprietary/lib/hw/keystore.default.so:/system/lib/hw/keystore.default.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioclient.so:/system/lib/libaudioclient.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiocompensationfilter.so:/system/lib/libaudiocompensationfilter.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiocomponentengine.so:/system/lib/libaudiocomponentengine.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiocustparam.so:/system/lib/libaudiocustparam.solibaudiodcrflt.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiodcrflt.so:/system/lib/libaudiodcrflt.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioeffect_jni.so:/system/lib/libaudioeffect_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioflinger.so:/system/lib/libaudioflinger.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiohal.so:/system/lib/libaudiohal.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiomanager.so:/system/lib/libaudiomanager.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicycustomextensions.so:/system/lib/libaudiopolicycustomextensions.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicyenginedefault.so:/system/lib/libaudiopolicyenginedefault.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicymanager.so:/system/lib/libaudiopolicymanager.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicymanagerdefault.so:/system/lib/libaudiopolicymanagerdefault.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiopolicyservice.so:/system/lib/libaudiopolicyservice.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioprimarydevicehalifclient.so:/system/lib/libaudioprimarydevicehalifclient.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioprocessing.so:/system/lib/libaudioprocessing.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudio-resampler.so:/system/lib/libaudio-resampler.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiospdif.so:/system/lib/libaudiospdif.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiotoolkit.so:/system/lib/libaudiotoolkit.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudioutils.so:/system/lib/libaudioutils.solibaudioutils.so \
    vendor/alps/8227l_demo/proprietary/lib/libaudiowhitelist.so:/system/lib/libaudiowhitelist.so \
    vendor/alps/8227l_demo/proprietary/lib/libbessound_hd_mtk.so:/system/lib/libbessound_hd_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libblisrc.so:/system/lib/libblisrc.so \
    vendor/alps/8227l_demo/proprietary/lib/libblisrc32.so:/system/lib/libblisrc32.so \
    vendor/alps/8227l_demo/proprietary/lib/libbluetoothem_mtk_system.so:/system/lib/libbluetoothem_mtk_system.so \
    vendor/alps/8227l_demo/proprietary/lib/libbluetooth_mtk_pure_system.so:/system/lib/libbluetooth_mtk_pure_system.so \
    vendor/alps/8227l_demo/proprietary/lib/libbluetooth_relayer_system.so:/system/lib/libbluetooth_relayer_system.so \
    vendor/alps/8227l_demo/proprietary/lib/libcamera2ndk.so:/system/lib/libcamera2ndk.so \
    vendor/alps/8227l_demo/proprietary/lib/libcamera_client.so:/system/lib/libcamera_client.so \
    vendor/alps/8227l_demo/proprietary/lib/libcamera_metadata.so:/system/lib/libcamera_metadata.so \
    vendor/alps/8227l_demo/proprietary/lib/libcameraservice.so:/system/lib/libcameraservice.so \
    vendor/alps/8227l_demo/proprietary/lib/libcustom_jni.so:/system/lib/libcustom_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libcustom_nvram_mtk.so:/system/lib/libcustom_nvram_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libcustom_prop.so:/system/lib/libcustom_prop.solibcustom_prop.so \
    vendor/alps/8227l_demo/proprietary/lib/libdrmframework.so:/system/lib/libdrmframework.so \
    vendor/alps/8227l_demo/proprietary/lib/libdrmframework_jni.so:/system/lib/libdrmframework_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libem_support_jni.so:/system/lib/libem_support_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libfile_op_mtk.so:/system/lib/libfile_op_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libfmjni.so:/system/lib/libfmjni.so \
    vendor/alps/8227l_demo/proprietary/lib/libfmq.so:/system/lib/libfmq.so \
    vendor/alps/8227l_demo/proprietary/lib/libGdmaScalerPipe.so:/system/lib/libGdmaScalerPipe.so \
    vendor/alps/8227l_demo/proprietary/lib/libgralloc_extra_sys.so:/system/lib/libgralloc_extra_sys.so \
    vendor/alps/8227l_demo/proprietary/lib/libgui.so:/system/lib/libgui.so \
    vendor/alps/8227l_demo/proprietary/lib/libgui_debug.so:/system/lib/libgui_debug.so \
    vendor/alps/8227l_demo/proprietary/lib/libhwbinder.so:/system/lib/libhwbinder.so \
    vendor/alps/8227l_demo/proprietary/lib/libhwm_mtk.so:/system/lib/libhwm_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libion.so:/system/lib/libion.so \
    vendor/alps/8227l_demo/proprietary/lib/libjpeg.so:/system/lib/libjpeg.so \
    vendor/alps/8227l_demo/proprietary/lib/libJpgDecPipe.so:/system/lib/libJpgDecPipe.so \
    vendor/alps/8227l_demo/proprietary/lib/libJpgEncPipe.so:/system/lib/libJpgEncPipe.so \
    vendor/alps/8227l_demo/proprietary/lib/libmemtrack.so:/system/lib/libmemtrack.so \
    vendor/alps/8227l_demo/proprietary/lib/libmhalImageCodec.so:/system/lib/libmhalImageCodec.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkavenhancements.so:/system/lib/libmtkavenhancements.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkbluetooth_jni.so:/system/lib/libmtkbluetooth_jni.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkbootanimation.so:/system/lib/libmtkbootanimation.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtk_drvb_sys.so:/system/lib/libmtk_drvb_sys.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtklimiter.so:/system/lib/libmtklimiter.so \
    vendor/alps/8227l_demo/proprietary/lib/libmtkshifter.so:/system/lib/libmtkshifter.so \
    vendor/alps/8227l_demo/proprietary/lib/libnvram_mtk.so:/system/lib/libnvram_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libnvram_platform_mtk.so:/system/lib/libnvram_platform_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libnvram_sec_mtk.so:/system/lib/libnvram_sec_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libRadioInterface.so:/system/lib/libRadioInterface.so \
    vendor/alps/8227l_demo/proprietary/lib/libradio_metadata.so:/system/lib/libradio_metadata.so \
    vendor/alps/8227l_demo/proprietary/lib/libsensor.so:/system/lib/libsensor.so \
    vendor/alps/8227l_demo/proprietary/lib/libsensorservice.so:/system/lib/libsensorservice.so \
    vendor/alps/8227l_demo/proprietary/lib/libsensorservicehidl.so:/system/lib/libsensorservicehidl.so \
    vendor/alps/8227l_demo/proprietary/lib/libshowlogo.so:/system/lib/libshowlogo.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright.so:/system/lib/libstagefright.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_amrnb_common.so:/system/lib/libstagefright_amrnb_common.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_enc_common.so:/system/lib/libstagefright_enc_common.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_flacdec.so:/system/lib/libstagefright_flacdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_foundation.so:/system/lib/libstagefright_foundation.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_httplive.so:/system/lib/libstagefright_httplive.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_http_support.so:/system/lib/libstagefright_http_support.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_omx.so:/system/lib/libstagefright_omx.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_omx_utils.so:/system/lib/libstagefright_omx_utils.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_aacdec.so:/system/lib/libstagefright_soft_aacdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_aacenc.so:/system/lib/libstagefright_soft_aacenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_amrdec.so:/system/lib/libstagefright_soft_amrdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_amrnbenc.so:/system/lib/libstagefright_soft_amrnbenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_amrwbenc.so:/system/lib/libstagefright_soft_amrwbenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_avcdec.so:/system/lib/libstagefright_soft_avcdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_avcenc.so:/system/lib/libstagefright_soft_avcenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_flacdec.so:/system/lib/libstagefright_soft_flacdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_flacenc.so:/system/lib/libstagefright_soft_flacenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_g711dec.so:/system/lib/libstagefright_soft_g711dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_gsmdec.so:/system/lib/libstagefright_soft_gsmdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_hevcdec.so:/system/lib/libstagefright_soft_hevcdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mp3dec.so:/system/lib/libstagefright_soft_mp3dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mpeg2dec.so:/system/lib/libstagefright_soft_mpeg2dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mpeg4dec.so:/system/lib/libstagefright_soft_mpeg4dec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_mpeg4enc.so:/system/lib/libstagefright_soft_mpeg4enc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_opusdec.so:/system/lib/libstagefright_soft_opusdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_rawdec.so:/system/lib/libstagefright_soft_rawdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_vorbisdec.so:/system/lib/libstagefright_soft_vorbisdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_vpxdec.so:/system/lib/libstagefright_soft_vpxdec.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_soft_vpxenc.so:/system/lib/libstagefright_soft_vpxenc.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_wfd_mtk.so:/system/lib/libstagefright_wfd_mtk.so \
    vendor/alps/8227l_demo/proprietary/lib/libstagefright_xmlparser.so:/system/lib/libstagefright_xmlparser.so \
    vendor/alps/8227l_demo/proprietary/lib/libSwJpgCodec.so:/system/lib/libSwJpgCodec.so \
    vendor/alps/8227l_demo/proprietary/lib/libui.so:/system/lib/libui.so \
    vendor/alps/8227l_demo/proprietary/lib/libui_ext_fwk.so:/system/lib/libui_ext_fwk.so \
    vendor/alps/8227l_demo/proprietary/lib/libusbdvr.so:/system/lib/libusbdvr.so \
    vendor/alps/8227l_demo/proprietary/lib/libusbhost.so:/system/lib/libusbhost.so