# Copyright (C) 2018-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/taimen/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),8227l_demo)

endif

# Release name
PRODUCT_RELEASE_NAME := 8227l_demo

# Inherit some common lineage stuff.
$(call inherit-product, vendor/lineage/config/common_full_phone.mk)

# Inherit device configuration
$(call inherit-product, device/alps/8227l_demo/device_8227l_demo.mk)

## Device identifier. This must come after all inclusions
PRODUCT_DEVICE := 8227l_demo
PRODUCT_NAME := lineage_8227l_demo
PRODUCT_BRAND := alps
PRODUCT_MODEL := 8227l_demo
PRODUCT_MANUFACTURER := alps
